//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="effectsForCaster" type="{}abilityEffect" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="effectsForTarget" type="{}abilityEffect" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="manaCost" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cooldown" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cooldownReamingTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ableToMiss" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "effectsForCaster",
    "effectsForTarget"
})
@XmlRootElement(name = "ability")
public class Ability {

    protected List<AbilityEffect> effectsForCaster;
    protected List<AbilityEffect> effectsForTarget;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "manaCost")
    protected Integer manaCost;
    @XmlAttribute(name = "cooldown")
    protected Integer cooldown;
    @XmlAttribute(name = "cooldownReamingTime")
    protected Integer cooldownReamingTime;
    @XmlAttribute(name = "ableToMiss")
    protected Boolean ableToMiss;

    /**
     * Gets the value of the effectsForCaster property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectsForCaster property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectsForCaster().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityEffect }
     * 
     * 
     */
    public List<AbilityEffect> getEffectsForCaster() {
        if (effectsForCaster == null) {
            effectsForCaster = new ArrayList<AbilityEffect>();
        }
        return this.effectsForCaster;
    }

    /**
     * Gets the value of the effectsForTarget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the effectsForTarget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectsForTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbilityEffect }
     * 
     * 
     */
    public List<AbilityEffect> getEffectsForTarget() {
        if (effectsForTarget == null) {
            effectsForTarget = new ArrayList<AbilityEffect>();
        }
        return this.effectsForTarget;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the manaCost property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getManaCost() {
        return manaCost;
    }

    /**
     * Sets the value of the manaCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setManaCost(Integer value) {
        this.manaCost = value;
    }

    /**
     * Gets the value of the cooldown property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCooldown() {
        return cooldown;
    }

    /**
     * Sets the value of the cooldown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCooldown(Integer value) {
        this.cooldown = value;
    }

    /**
     * Gets the value of the cooldownReamingTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCooldownReamingTime() {
        return cooldownReamingTime;
    }

    /**
     * Sets the value of the cooldownReamingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCooldownReamingTime(Integer value) {
        this.cooldownReamingTime = value;
    }

    /**
     * Gets the value of the ableToMiss property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbleToMiss() {
        return ableToMiss;
    }

    /**
     * Sets the value of the ableToMiss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbleToMiss(Boolean value) {
        this.ableToMiss = value;
    }

}
