//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abilityEvents.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="abilityEvents">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TurnStart"/>
 *     &lt;enumeration value="HealBeforeTake"/>
 *     &lt;enumeration value="HealAfterTake"/>
 *     &lt;enumeration value="DamageBeforeTake"/>
 *     &lt;enumeration value="DamageAfterTake"/>
 *     &lt;enumeration value="OverTimeBeforeTake"/>
 *     &lt;enumeration value="OverTimeBeforeUse"/>
 *     &lt;enumeration value="AbilityBeforeUse"/>
 *     &lt;enumeration value="AbilityAfterUse"/>
 *     &lt;enumeration value="TurnEnd"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "abilityEvents")
@XmlEnum
public enum AbilityEvents {

    @XmlEnumValue("TurnStart")
    TURN_START("TurnStart"),
    @XmlEnumValue("HealBeforeTake")
    HEAL_BEFORE_TAKE("HealBeforeTake"),
    @XmlEnumValue("HealAfterTake")
    HEAL_AFTER_TAKE("HealAfterTake"),
    @XmlEnumValue("DamageBeforeTake")
    DAMAGE_BEFORE_TAKE("DamageBeforeTake"),
    @XmlEnumValue("DamageAfterTake")
    DAMAGE_AFTER_TAKE("DamageAfterTake"),
    @XmlEnumValue("OverTimeBeforeTake")
    OVER_TIME_BEFORE_TAKE("OverTimeBeforeTake"),
    @XmlEnumValue("OverTimeBeforeUse")
    OVER_TIME_BEFORE_USE("OverTimeBeforeUse"),
    @XmlEnumValue("AbilityBeforeUse")
    ABILITY_BEFORE_USE("AbilityBeforeUse"),
    @XmlEnumValue("AbilityAfterUse")
    ABILITY_AFTER_USE("AbilityAfterUse"),
    @XmlEnumValue("TurnEnd")
    TURN_END("TurnEnd");
    private final String value;

    AbilityEvents(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AbilityEvents fromValue(String v) {
        for (AbilityEvents c: AbilityEvents.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
