//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abilityEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abilityEffect">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spellEffect">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="ableToMiss" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="magicSchool" type="{}magicSchools" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abilityEffect", propOrder = {
    "spellEffect"
})
@XmlSeeAlso({
    Damage.class,
    Heal.class,
    OverTime.class
})
public abstract class AbilityEffect {

    @XmlElement(required = true)
    protected AbilityEffect.SpellEffect spellEffect;

    /**
     * Gets the value of the spellEffect property.
     * 
     * @return
     *     possible object is
     *     {@link AbilityEffect.SpellEffect }
     *     
     */
    public AbilityEffect.SpellEffect getSpellEffect() {
        return spellEffect;
    }

    /**
     * Sets the value of the spellEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbilityEffect.SpellEffect }
     *     
     */
    public void setSpellEffect(AbilityEffect.SpellEffect value) {
        this.spellEffect = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="ableToMiss" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="magicSchool" type="{}magicSchools" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SpellEffect {

        @XmlAttribute(name = "id")
        protected Integer id;
        @XmlAttribute(name = "ableToMiss")
        protected Boolean ableToMiss;
        @XmlAttribute(name = "magicSchool")
        protected MagicSchools magicSchool;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the ableToMiss property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAbleToMiss() {
            return ableToMiss;
        }

        /**
         * Sets the value of the ableToMiss property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAbleToMiss(Boolean value) {
            this.ableToMiss = value;
        }

        /**
         * Gets the value of the magicSchool property.
         * 
         * @return
         *     possible object is
         *     {@link MagicSchools }
         *     
         */
        public MagicSchools getMagicSchool() {
            return magicSchool;
        }

        /**
         * Sets the value of the magicSchool property.
         * 
         * @param value
         *     allowed object is
         *     {@link MagicSchools }
         *     
         */
        public void setMagicSchool(MagicSchools value) {
            this.magicSchool = value;
        }

    }

}
