//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abilityEffectEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abilityEffectEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="casterId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="abilityEffectId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="targetId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="magicSchool" type="{}magicSchools" />
 *       &lt;attribute name="hit" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="modificator" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abilityEffectEvent")
public class AbilityEffectEvent {

    @XmlAttribute(name = "casterId")
    protected Integer casterId;
    @XmlAttribute(name = "abilityEffectId")
    protected Integer abilityEffectId;
    @XmlAttribute(name = "targetId")
    protected Integer targetId;
    @XmlAttribute(name = "magicSchool")
    protected MagicSchools magicSchool;
    @XmlAttribute(name = "hit")
    protected Double hit;
    @XmlAttribute(name = "modificator")
    protected Double modificator;
    @XmlAttribute(name = "value")
    protected Double value;

    /**
     * Gets the value of the casterId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCasterId() {
        return casterId;
    }

    /**
     * Sets the value of the casterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCasterId(Integer value) {
        this.casterId = value;
    }

    /**
     * Gets the value of the abilityEffectId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAbilityEffectId() {
        return abilityEffectId;
    }

    /**
     * Sets the value of the abilityEffectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAbilityEffectId(Integer value) {
        this.abilityEffectId = value;
    }

    /**
     * Gets the value of the targetId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTargetId(Integer value) {
        this.targetId = value;
    }

    /**
     * Gets the value of the magicSchool property.
     * 
     * @return
     *     possible object is
     *     {@link MagicSchools }
     *     
     */
    public MagicSchools getMagicSchool() {
        return magicSchool;
    }

    /**
     * Sets the value of the magicSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagicSchools }
     *     
     */
    public void setMagicSchool(MagicSchools value) {
        this.magicSchool = value;
    }

    /**
     * Gets the value of the hit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHit() {
        return hit;
    }

    /**
     * Sets the value of the hit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHit(Double value) {
        this.hit = value;
    }

    /**
     * Gets the value of the modificator property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getModificator() {
        return modificator;
    }

    /**
     * Sets the value of the modificator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setModificator(Double value) {
        this.modificator = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValue(Double value) {
        this.value = value;
    }

}
