//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attributeTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="attributeTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BaseHp"/>
 *     &lt;enumeration value="BonusHp"/>
 *     &lt;enumeration value="ActualHp"/>
 *     &lt;enumeration value="BaseMana"/>
 *     &lt;enumeration value="BonusMana"/>
 *     &lt;enumeration value="MaxMana"/>
 *     &lt;enumeration value="ActualMana"/>
 *     &lt;enumeration value="BaseStrength"/>
 *     &lt;enumeration value="BonusStrength"/>
 *     &lt;enumeration value="Strength"/>
 *     &lt;enumeration value="BaseAgility"/>
 *     &lt;enumeration value="BonusAgility"/>
 *     &lt;enumeration value="Agility"/>
 *     &lt;enumeration value="BaseIntellect"/>
 *     &lt;enumeration value="BonusIntellect"/>
 *     &lt;enumeration value="Intellect"/>
 *     &lt;enumeration value="BonusAttackPower"/>
 *     &lt;enumeration value="AttackPower"/>
 *     &lt;enumeration value="BonusMaxDamage"/>
 *     &lt;enumeration value="MaxDamage"/>
 *     &lt;enumeration value="BonusMinDamage"/>
 *     &lt;enumeration value="MinDamage"/>
 *     &lt;enumeration value="Armor"/>
 *     &lt;enumeration value="BonusDodgeChance"/>
 *     &lt;enumeration value="DodgeChance"/>
 *     &lt;enumeration value="BonusCritChance"/>
 *     &lt;enumeration value="CritChance"/>
 *     &lt;enumeration value="MagicResist"/>
 *     &lt;enumeration value="BonusSpellPower"/>
 *     &lt;enumeration value="SpellPower"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "attributeTypes")
@XmlEnum
public enum AttributeTypes {

    @XmlEnumValue("BaseHp")
    BASE_HP("BaseHp"),
    @XmlEnumValue("BonusHp")
    BONUS_HP("BonusHp"),
    @XmlEnumValue("ActualHp")
    ACTUAL_HP("ActualHp"),
    @XmlEnumValue("BaseMana")
    BASE_MANA("BaseMana"),
    @XmlEnumValue("BonusMana")
    BONUS_MANA("BonusMana"),
    @XmlEnumValue("MaxMana")
    MAX_MANA("MaxMana"),
    @XmlEnumValue("ActualMana")
    ACTUAL_MANA("ActualMana"),
    @XmlEnumValue("BaseStrength")
    BASE_STRENGTH("BaseStrength"),
    @XmlEnumValue("BonusStrength")
    BONUS_STRENGTH("BonusStrength"),
    @XmlEnumValue("Strength")
    STRENGTH("Strength"),
    @XmlEnumValue("BaseAgility")
    BASE_AGILITY("BaseAgility"),
    @XmlEnumValue("BonusAgility")
    BONUS_AGILITY("BonusAgility"),
    @XmlEnumValue("Agility")
    AGILITY("Agility"),
    @XmlEnumValue("BaseIntellect")
    BASE_INTELLECT("BaseIntellect"),
    @XmlEnumValue("BonusIntellect")
    BONUS_INTELLECT("BonusIntellect"),
    @XmlEnumValue("Intellect")
    INTELLECT("Intellect"),
    @XmlEnumValue("BonusAttackPower")
    BONUS_ATTACK_POWER("BonusAttackPower"),
    @XmlEnumValue("AttackPower")
    ATTACK_POWER("AttackPower"),
    @XmlEnumValue("BonusMaxDamage")
    BONUS_MAX_DAMAGE("BonusMaxDamage"),
    @XmlEnumValue("MaxDamage")
    MAX_DAMAGE("MaxDamage"),
    @XmlEnumValue("BonusMinDamage")
    BONUS_MIN_DAMAGE("BonusMinDamage"),
    @XmlEnumValue("MinDamage")
    MIN_DAMAGE("MinDamage"),
    @XmlEnumValue("Armor")
    ARMOR("Armor"),
    @XmlEnumValue("BonusDodgeChance")
    BONUS_DODGE_CHANCE("BonusDodgeChance"),
    @XmlEnumValue("DodgeChance")
    DODGE_CHANCE("DodgeChance"),
    @XmlEnumValue("BonusCritChance")
    BONUS_CRIT_CHANCE("BonusCritChance"),
    @XmlEnumValue("CritChance")
    CRIT_CHANCE("CritChance"),
    @XmlEnumValue("MagicResist")
    MAGIC_RESIST("MagicResist"),
    @XmlEnumValue("BonusSpellPower")
    BONUS_SPELL_POWER("BonusSpellPower"),
    @XmlEnumValue("SpellPower")
    SPELL_POWER("SpellPower");
    private final String value;

    AttributeTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttributeTypes fromValue(String v) {
        for (AttributeTypes c: AttributeTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
