//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for buff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="buff">
 *   &lt;complexContent>
 *     &lt;extension base="{}overTime">
 *       &lt;attribute name="attTarget" type="{}attributeTypes" />
 *       &lt;attribute name="bonus" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buff")
public class Buff
    extends OverTime
{

    @XmlAttribute(name = "attTarget")
    protected AttributeTypes attTarget;
    @XmlAttribute(name = "bonus")
    protected Double bonus;

    /**
     * Gets the value of the attTarget property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeTypes }
     *     
     */
    public AttributeTypes getAttTarget() {
        return attTarget;
    }

    /**
     * Sets the value of the attTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeTypes }
     *     
     */
    public void setAttTarget(AttributeTypes value) {
        this.attTarget = value;
    }

    /**
     * Gets the value of the bonus property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBonus() {
        return bonus;
    }

    /**
     * Sets the value of the bonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBonus(Double value) {
        this.bonus = value;
    }

}
