//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conditionEffect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conditionEffect">
 *   &lt;complexContent>
 *     &lt;extension base="{}overTime">
 *       &lt;sequence>
 *         &lt;element name="effectEventCheck" type="{}abilityEffectEvent"/>
 *         &lt;element name="effectEventChange" type="{}abilityEffectEvent"/>
 *       &lt;/sequence>
 *       &lt;attribute name="removeAfterTrigger" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="effectIdToUse" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="spellReflect" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="event" type="{}abilityEvents" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conditionEffect", propOrder = {
    "effectEventCheck",
    "effectEventChange"
})
public class ConditionEffect
    extends OverTime
{

    @XmlElement(required = true)
    protected AbilityEffectEvent effectEventCheck;
    @XmlElement(required = true)
    protected AbilityEffectEvent effectEventChange;
    @XmlAttribute(name = "removeAfterTrigger")
    protected Double removeAfterTrigger;
    @XmlAttribute(name = "effectIdToUse")
    protected Integer effectIdToUse;
    @XmlAttribute(name = "spellReflect")
    protected Double spellReflect;
    @XmlAttribute(name = "event")
    protected AbilityEvents event;

    /**
     * Gets the value of the effectEventCheck property.
     * 
     * @return
     *     possible object is
     *     {@link AbilityEffectEvent }
     *     
     */
    public AbilityEffectEvent getEffectEventCheck() {
        return effectEventCheck;
    }

    /**
     * Sets the value of the effectEventCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbilityEffectEvent }
     *     
     */
    public void setEffectEventCheck(AbilityEffectEvent value) {
        this.effectEventCheck = value;
    }

    /**
     * Gets the value of the effectEventChange property.
     * 
     * @return
     *     possible object is
     *     {@link AbilityEffectEvent }
     *     
     */
    public AbilityEffectEvent getEffectEventChange() {
        return effectEventChange;
    }

    /**
     * Sets the value of the effectEventChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbilityEffectEvent }
     *     
     */
    public void setEffectEventChange(AbilityEffectEvent value) {
        this.effectEventChange = value;
    }

    /**
     * Gets the value of the removeAfterTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRemoveAfterTrigger() {
        return removeAfterTrigger;
    }

    /**
     * Sets the value of the removeAfterTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRemoveAfterTrigger(Double value) {
        this.removeAfterTrigger = value;
    }

    /**
     * Gets the value of the effectIdToUse property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEffectIdToUse() {
        return effectIdToUse;
    }

    /**
     * Sets the value of the effectIdToUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEffectIdToUse(Integer value) {
        this.effectIdToUse = value;
    }

    /**
     * Gets the value of the spellReflect property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpellReflect() {
        return spellReflect;
    }

    /**
     * Sets the value of the spellReflect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpellReflect(Double value) {
        this.spellReflect = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link AbilityEvents }
     *     
     */
    public AbilityEvents getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbilityEvents }
     *     
     */
    public void setEvent(AbilityEvents value) {
        this.event = value;
    }

}
