//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for damage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="damage">
 *   &lt;complexContent>
 *     &lt;extension base="{}abilityEffect">
 *       &lt;attribute name="minEffect" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="maxEffect" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="modAtt" type="{}attributeTypes" />
 *       &lt;attribute name="ableToCrit" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="percentage" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "damage")
public class Damage
    extends AbilityEffect
{

    @XmlAttribute(name = "minEffect")
    protected Double minEffect;
    @XmlAttribute(name = "maxEffect")
    protected Double maxEffect;
    @XmlAttribute(name = "multiplier")
    protected Double multiplier;
    @XmlAttribute(name = "modAtt")
    protected AttributeTypes modAtt;
    @XmlAttribute(name = "ableToCrit")
    protected Boolean ableToCrit;
    @XmlAttribute(name = "percentage")
    protected Boolean percentage;

    /**
     * Gets the value of the minEffect property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinEffect() {
        return minEffect;
    }

    /**
     * Sets the value of the minEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinEffect(Double value) {
        this.minEffect = value;
    }

    /**
     * Gets the value of the maxEffect property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxEffect() {
        return maxEffect;
    }

    /**
     * Sets the value of the maxEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxEffect(Double value) {
        this.maxEffect = value;
    }

    /**
     * Gets the value of the multiplier property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMultiplier() {
        return multiplier;
    }

    /**
     * Sets the value of the multiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMultiplier(Double value) {
        this.multiplier = value;
    }

    /**
     * Gets the value of the modAtt property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeTypes }
     *     
     */
    public AttributeTypes getModAtt() {
        return modAtt;
    }

    /**
     * Sets the value of the modAtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeTypes }
     *     
     */
    public void setModAtt(AttributeTypes value) {
        this.modAtt = value;
    }

    /**
     * Gets the value of the ableToCrit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbleToCrit() {
        return ableToCrit;
    }

    /**
     * Sets the value of the ableToCrit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbleToCrit(Boolean value) {
        this.ableToCrit = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPercentage(Boolean value) {
        this.percentage = value;
    }

}
