//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for heal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="heal">
 *   &lt;complexContent>
 *     &lt;extension base="{}abilityEffect">
 *       &lt;attribute name="minEffect" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="percentage" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "heal")
public class Heal
    extends AbilityEffect
{

    @XmlAttribute(name = "minEffect")
    protected Double minEffect;
    @XmlAttribute(name = "percentage")
    protected Boolean percentage;

    /**
     * Gets the value of the minEffect property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinEffect() {
        return minEffect;
    }

    /**
     * Sets the value of the minEffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinEffect(Double value) {
        this.minEffect = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPercentage(Boolean value) {
        this.percentage = value;
    }

}
