//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.10 at 09:38:08 AM CET 
//


package abc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the abc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: abc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link Damage }
     * 
     */
    public Damage createDamage() {
        return new Damage();
    }

    /**
     * Create an instance of {@link Shield }
     * 
     */
    public Shield createShield() {
        return new Shield();
    }

    /**
     * Create an instance of {@link Heal }
     * 
     */
    public Heal createHeal() {
        return new Heal();
    }

    /**
     * Create an instance of {@link ConditionEffect }
     * 
     */
    public ConditionEffect createConditionEffect() {
        return new ConditionEffect();
    }

    /**
     * Create an instance of {@link Buff }
     * 
     */
    public Buff createBuff() {
        return new Buff();
    }

    /**
     * Create an instance of {@link AbilityEffectEvent }
     * 
     */
    public AbilityEffectEvent createAbilityEffectEvent() {
        return new AbilityEffectEvent();
    }

    /**
     * Create an instance of {@link abc.AbilityEffect.SpellEffect }
     * 
     */
    public abc.AbilityEffect.SpellEffect createAbilityEffectSpellEffect() {
        return new abc.AbilityEffect.SpellEffect();
    }

}
